/* ============================================================
   ECHOBREAKER — Content Pool (60 Unique Posts)
   Balanced: 7 tones, EP 1-10, recency 1-72h, 16 quizzes
   ============================================================ */

const CONTENT_POOL = [
  {
    "id": "post_001",
    "type": "text",
    "headline": "New Study Links Daily Walking to 30% Better Sleep Quality",
    "body": "Researchers at a major university found that just 20 minutes of walking per day significantly improved sleep patterns in adults aged 18-65. The study followed 2,400 participants over 12 months.",
    "category": "health",
    "emotional_tone": "joy",
    "engagement_potential": 5,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_001.png",
    "fallbackText": "Sleep & Daily Walking",
    "educationalNote": "This post models a credible, evidence-based health claim backed by a large sample (n=2,400) and a named institution. Contrast it with post_002 to show students how legitimate research is framed differently from sensationalist content. Discussion prompt: What signals tell you this source is trustworthy?",
    "quiz": {
      "question": "Why would the algorithm push this post to a user who already liked health content?",
      "options": [
        "Because the post went viral and got millions of shares",
        "Because the algorithm matched the post's 'health' category to the user's established affinity",
        "Because it was the most recently published post in the feed"
      ],
      "correctIndex": 1,
      "explanation": "Category affinity (weight 0.40) is the strongest signal in the scoring formula. Once a user engages with health content, the algorithm amplifies similar posts   -   regardless of their credibility."
    },
    "publishedHoursAgo": 1,
    "headline_fr": "Une étude associe la marche quotidienne à une amélioration du sommeil de 30%",
    "body_fr": "Des chercheurs ont découvert que 20 minutes de marche par jour améliorent significativement le sommeil.",
    "headline_es": "Un estudio vincula la caminata diaria con una mejora del 30% en el sueño",
    "body_es": "Investigadores descubrieron que 20 minutos de caminata al día mejoran significativamente el sueño."
  },
  {
    "id": "post_002",
    "type": "text",
    "headline": "MIRACLE BERRY Extract ELIMINATES All Chronic Pain in 48 Hours!",
    "body": "Thousands are ditching their medication after discovering this one weird fruit from the Amazon. Big Pharma doesn't want you to know about this natural cure that doctors are calling 'impossible.'",
    "category": "health",
    "emotional_tone": "surprise",
    "engagement_potential": 10,
    "source_credibility": 1,
    "is_misleading": true,
    "imageUrl": "img/post_002.png",
    "fallbackText": "Miracle Cure Claim",
    "educationalNote": "This post uses classic misinformation framing: ALL-CAPS urgency, vague authority ('doctors are saying'), conspiracy framing ('Big Pharma doesn't want you to know'), and an implausible claim (eliminates all pain in 48h). Despite low credibility (1/10), its high emotional valence (surprise) gives it an engagement_potential of 9   -   meaning the algorithm will heavily promote it. Key insight for students: high engagement â‰  high accuracy.",
    "quiz": {
      "question": "Despite being misleading, why does the algorithm rank this post highly?",
      "options": [
        "The algorithm checks facts before promoting content",
        "High emotional resonance (surprise/fear) and high engagement potential (9/10) outweigh credibility in the scoring formula",
        "The post was sponsored and paid for placement"
      ],
      "correctIndex": 1,
      "explanation": "The scoring formula weighs emotional resonance at 0.30 and engagement potential at 0.20   -   but does NOT include a credibility check. This is the core lesson: algorithms optimize for attention, not accuracy."
    },
    "publishedHoursAgo": 1,
    "headline_fr": "L'extrait de Baie Miracle ÉLIMINE toute douleur chronique en 48 heures !",
    "body_fr": "Des milliers de personnes abandonnent leurs médicaments après avoir découvert ce fruit d'Amazonie.",
    "headline_es": "¡El extracto de Baya Milagrosa ELIMINA todo dolor crónico en 48 horas!",
    "body_es": "Miles de personas dejan sus medicamentos tras descubrir esta fruta de la Amazonia."
  },
  {
    "id": "post_003",
    "type": "text",
    "headline": "Mental Health Days Now Covered Under New Wellness Guidelines",
    "body": "Updated workplace guidelines now recommend employers offer at least 3 mental health days per quarter. Experts say this could reduce burnout rates by up to 40%.",
    "category": "health",
    "emotional_tone": "outrage",
    "engagement_potential": 6,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_003.png",
    "fallbackText": "Mental Health Policy",
    "educationalNote": "This post covers a genuine policy development with measurable impact claims (40% burnout reduction). It has moderate engagement (6/10)   -   not sensationalist enough to go viral, but credible enough to be valuable. Discuss with students: why might accurate, policy-oriented posts struggle to compete with sensational content in algorithmic feeds?",
    "quiz": {
      "question": "A new student opens the app. Why might this post appear lower in their feed than post_002, even though it is more credible?",
      "options": [
        "Because wellness content is penalized by the algorithm",
        "Because its emotional tone (joy) and engagement potential (6) score lower than post_002's emotional surprise + potential (9)",
        "Because it was published earlier and the recency boost expired"
      ],
      "correctIndex": 1,
      "explanation": "Emotional resonance and engagement potential together account for 50% of the score. A surprising or fear-inducing post will almost always outrank a calm, credible post   -   this is the algorithmic bias at the heart of EchoBreaker's lesson."
    },
    "publishedHoursAgo": 3,
    "headline_fr": "Les journées de santé mentale couvertes par les nouvelles directives",
    "body_fr": "Des recommandations conseillent 3 jours de repos mental par trimestre pour réduire le burn-out.",
    "headline_es": "Días de salud mental cubiertos por las nuevas pautas de bienestar",
    "body_es": "Las pautas recomendadas sugieren 3 días de descanso mental al trimestre para prevenir el agotamiento."
  },
  {
    "id": "post_004",
    "type": "text",
    "headline": "Mediterranean Diet Linked to Lower Risk of Heart Disease",
    "body": "A comprehensive 5-year review of dietary studies confirms that the Mediterranean diet, rich in olive oil, fish, and vegetables, reduces cardiovascular risk by 25%.",
    "category": "health",
    "emotional_tone": "neutral",
    "engagement_potential": 2,
    "source_credibility": 9,
    "is_misleading": false,
    "imageUrl": "img/post_004.png",
    "publishedHoursAgo": 18,
    "quiz": {
      "question": "This post has credibility 9/10 but engagement only 2/10. What does the algorithm prioritize?",
      "options": [
        "Credibility — algorithms promote trustworthy sources",
        "Engagement potential — algorithms promote what gets clicks, not what's accurate",
        "Recency — only the newest posts appear"
      ],
      "correctIndex": 1,
      "explanation": "The algorithm has no credibility parameter. Dry but accurate content (EP=2) gets outranked by sensational false content (EP=10)."
    },
    "headline_fr": "Le régime méditerranéen réduit le risque cardiaque de 25%",
    "body_fr": "Une étude confirme les bienfaits de l'huile d'olive et des légumes sur la santé cardiovasculaire.",
    "headline_es": "La dieta mediterránea reduce el riesgo cardíaco un 25%",
    "body_es": "Un estudio confirma los beneficios del aceite de oliva y verduras en la salud cardiovascular."
  },
  {
    "id": "post_005",
    "type": "text",
    "headline": "Screen Time Before Bed Disrupts Sleep Hormones, Study Confirms",
    "body": "Blue light from phones and tablets suppresses melatonin production by up to 58%. Researchers recommend a 30-minute screen-free period before sleep.",
    "category": "health",
    "emotional_tone": "fear",
    "engagement_potential": 7,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_005.png",
    "publishedHoursAgo": 8,
    "quiz": {
      "question": "This credible post uses 'fear' tone. How does fear affect its algorithmic score?",
      "options": [
        "Fear reduces the score because algorithms avoid negative content",
        "Fear increases emotional resonance (30% weight), boosting even credible content",
        "Fear has no effect on scoring"
      ],
      "correctIndex": 1,
      "explanation": "Fear triggers 30% of the score via emotional resonance. This incentivizes framing even good science in alarming ways."
    },
    "headline_fr": "L'écran avant le coucher perturbe la mélatonine et le sommeil",
    "body_fr": "La lumière bleue réduit la sécrétion de mélatonine de 58%. Les experts conseillent 30 min sans écran.",
    "headline_es": "El tiempo de pantalla antes de dormir altera las hormonas del sueño",
    "body_es": "La luz azul reduce la melatonina un 58%. Se recomienda apagar las pantallas 30 minutos antes."
  },
  {
    "id": "post_006",
    "type": "text",
    "headline": "EXPOSED: The Ingredient in Your Toothpaste That's Slowly Poisoning You",
    "body": "A viral social media post claims fluoride in toothpaste causes brain damage and lower IQ scores. 'They've been lying to us for decades,' says one influencer with 2M followers.",
    "category": "health",
    "emotional_tone": "outrage",
    "engagement_potential": 9,
    "source_credibility": 2,
    "is_misleading": true,
    "imageUrl": "img/post_006.png",
    "educationalNote": "This post exemplifies sensationalist health misinformation. It uses fear-inducing keywords ('EXPOSED', 'Slowly Poisoning You') and cites an influencer rather than peer-reviewed medical consensus. Key insight for students: follower count does not equal scientific authority.",
    "quiz": {
      "question": "Why does the algorithm promote this post despite its low credibility (2/10)?",
      "options": [
        "Because the claim has been verified by medical consensus",
        "Because outrage emotion and high engagement potential (8/10) boost its algorithmic score",
        "Because toothpaste companies paid the algorithm to promote it"
      ],
      "correctIndex": 1,
      "explanation": "The algorithm rewards content that triggers strong emotional reactions (outrage/fear) because it keeps users scrolling. Credibility is not factored into the recommendation score."
    },
    "publishedHoursAgo": 2,
    "headline_fr": "RÉVÉLATION : L'ingrédient de votre dentifrice qui vous empoisonne",
    "body_fr": "Un post viral prétend que le fluor est dangereux, mais les spécialistes rappellent la sécurité des doses.",
    "headline_es": "ALERTA: El ingrediente en tu pasta de dientes que te envenena",
    "body_es": "Un mensaje viral afirma que el flúor es tóxico, pero los expertos confirman la seguridad regulada."
  },
  {
    "id": "post_007",
    "type": "text",
    "headline": "Regular Exercise Boosts Immune System Response by 40%",
    "body": "Moderate exercise 3-4 times per week enhances the body's ability to fight infections. The effect is strongest for consistent exercisers over age 40.",
    "category": "health",
    "emotional_tone": "sadness",
    "engagement_potential": 2,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_007.png",
    "publishedHoursAgo": 15,
  },
  {
    "id": "post_008",
    "type": "text",
    "headline": "New Guidelines Recommend More Vitamin D for Northern Climates",
    "body": "Health authorities updated their Vitamin D recommendations, suggesting higher daily intake for populations living above 45° latitude due to reduced sun exposure.",
    "category": "health",
    "emotional_tone": "neutral",
    "engagement_potential": 1,
    "source_credibility": 9,
    "is_misleading": false,
    "imageUrl": "img/post_008.png",
    "publishedHoursAgo": 48,
    "quiz": {
      "question": "This post has the lowest engagement_potential (1). Where does it appear?",
      "options": [
        "At the top — low-engagement content is promoted for balance",
        "Near the bottom — engagement is 20% of the score",
        "It gets hidden completely"
      ],
      "correctIndex": 1,
      "explanation": "Low EP doesn't mean invisible, but the 0.20 weight pulls the score down. Only strong user affinity can rescue it."
    },
  },
  {
    "id": "post_009",
    "type": "text",
    "headline": "Hydration Study Shows Most People Don't Drink Enough Water",
    "body": "A survey of 10,000 adults found that 75% consume less water than recommended. Even mild dehydration can reduce cognitive performance by 15%.",
    "category": "health",
    "emotional_tone": "outrage",
    "engagement_potential": 6,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_009.png",
    "publishedHoursAgo": 10,
  },
  {
    "id": "post_010",
    "type": "text",
    "headline": "Stretching Before Bed Reduces Next-Day Muscle Soreness",
    "body": "Sports medicine researchers found that a simple 10-minute stretching routine before sleep reduced muscle stiffness and pain the following morning by 35%.",
    "category": "health",
    "emotional_tone": "fear",
    "engagement_potential": 4,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_010.png",
    "publishedHoursAgo": 20,
  },
  {
    "id": "post_011",
    "type": "text",
    "headline": "City Council Approves New Public Transport Expansion Plan",
    "body": "The city council voted 8-3 to approve a $2 billion public transit expansion, adding 12 new bus routes and 3 light rail lines over the next 5 years.",
    "category": "politics",
    "emotional_tone": "neutral",
    "engagement_potential": 2,
    "imageUrl": "img/post_011.png",
    "publishedHoursAgo": 48,
  },
  {
    "id": "post_012",
    "type": "text",
    "headline": "WARNING: Popular Mobile Apps Are Secretly Recording Your Audio 24/7!",
    "body": "Viral posts claim smartphone microphones are constantly listening to private conversations to serve targeted ads. Security researchers confirm apps only listen when explicit permissions are granted.",
    "category": "technology",
    "emotional_tone": "fear",
    "engagement_potential": 10,
    "source_credibility": 2,
    "is_misleading": true,
    "imageUrl": "img/post_012.png",
    "publishedHoursAgo": 1,
    "quiz": {
      "question": "This misleading post (credibility=2) has EP=10. What happens when a user likes it?",
      "options": [
        "The algorithm detects misinformation and stops promoting it",
        "The algorithm amplifies similar tech+fear content — it cannot tell credible from misleading",
        "Nothing — likes don't affect the feed"
      ],
      "correctIndex": 1,
      "explanation": "Every 'like' teaches the algorithm the user wants more of this category and tone. It cannot distinguish credible from misleading likes."
    },
    "headline_fr": "AVERTISSEMENT : Des applications enregistrent votre audio 24h/24 !",
    "body_fr": "Des rumeurs affirment que le micro écoute en permanence, mais les experts confirment l'accès réglementé.",
    "headline_es": "ADVERTENCIA: ¡Aplicaciones graban tu audio las 24 horas del día!",
    "body_es": "Publicaciones virales afirman que el micrófono escucha continuamente, pero los expertos lo desmienten."
  },
  {
    "id": "post_013",
    "type": "text",
    "headline": "New Education Bill Proposes Free School Meals for All Students",
    "body": "A bipartisan proposal would extend free breakfast and lunch programs to all public school students regardless of income. The bill has support from both sides of the aisle.",
    "category": "politics",
    "emotional_tone": "joy",
    "engagement_potential": 5,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_013.png",
    "educationalNote": "This post models credible policy reporting. It cites a bipartisan legislative proposal with clear impact scope. Contrast this with post_012 or post_014 to show students how legitimate public policy news differs from sensational outrage bait.",
    "quiz": {
      "question": "Why might a calm, positive news story like this receive fewer algorithmic impressions than a sensational political scandal?",
      "options": [
        "Because education news is banned by social media platforms",
        "Because algorithms prioritize high emotional valence (anger/fear) over calm, positive policy developments",
        "Because students don't use social media during school hours"
      ],
      "correctIndex": 1,
      "explanation": "Sensational or anger-inducing headlines generate 3x higher click-through rates. Algorithms optimize for user dwell time and emotional engagement rather than educational value or positive news."
    },
    "publishedHoursAgo": 2,
  },
  {
    "id": "post_014",
    "type": "text",
    "headline": "VIRAL TRICK: Typing This 4-Digit Code Doubles Your Wi-Fi Speed Instantly",
    "body": "A trending video claims entering a hidden secret code into your router settings instantly doubles internet bandwidth. IT experts confirm the code is completely fake and does nothing.",
    "category": "technology",
    "emotional_tone": "surprise",
    "engagement_potential": 9,
    "source_credibility": 2,
    "is_misleading": true,
    "imageUrl": "img/post_014.png",
    "educationalNote": "This post illustrates viral tech-bait. It uses 'VIRAL TRICK' and 'Instantly' to exploit curiosity and technical illiteracy. Key insight for students: quick-fix technical claims are almost always engagement traps.",
    "quiz": {
      "question": "Why does a fake 4-digit Wi-Fi code post get millions of shares?",
      "options": [
        "Because secret codes are hidden in all consumer routers",
        "Because the headline triggers curiosity and promises high reward with low effort",
        "Because Wi-Fi providers pay influencers to share secret shortcuts"
      ],
      "correctIndex": 1,
      "explanation": "Engagement algorithms promote content that drives instant clicks. High curiosity + zero effort promises generate massive viral sharing before anyone tests the claim."
    },
    "publishedHoursAgo": 2,
  },
  {
    "id": "post_015",
    "type": "text",
    "headline": "International Climate Summit Reaches Historic Agreement",
    "body": "After 10 days of negotiations, 140 nations agreed to reduce carbon emissions by 45% by 2035. Environmental groups called it 'a step in the right direction.'",
    "category": "politics",
    "emotional_tone": "anger",
    "engagement_potential": 5,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_015.png",
    "publishedHoursAgo": 8,
  },
  {
    "id": "post_016",
    "type": "text",
    "headline": "Local Elections See Record Youth Voter Turnout at 62%",
    "body": "Young voters aged 18-25 turned out in record numbers for municipal elections, driven by issues like housing affordability and public transit access.",
    "category": "politics",
    "emotional_tone": "anger",
    "engagement_potential": 5,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_016.png",
    "publishedHoursAgo": 12,
  },
  {
    "id": "post_017",
    "type": "text",
    "headline": "New Policy Requires Government Websites to Be Fully Accessible",
    "body": "Starting next year, all government digital services must meet accessibility standards for people with disabilities. The measure affects over 12,000 websites.",
    "category": "politics",
    "emotional_tone": "sadness",
    "engagement_potential": 1,
    "source_credibility": 9,
    "imageUrl": "img/post_017.png",
    "publishedHoursAgo": 36,
  },
  {
    "id": "post_019",
    "type": "text",
    "headline": "Community Policing Program Reduces Neighborhood Crime by 18%",
    "body": "A pilot program pairing police officers with community leaders in 6 neighborhoods showed significant crime reduction and improved public trust in law enforcement.",
    "category": "politics",
    "emotional_tone": "anger",
    "engagement_potential": 4,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_019.png",
    "publishedHoursAgo": 20,
  },
  {
    "id": "post_020",
    "type": "text",
    "headline": "Parliament Debates Digital Privacy Rights for Minors",
    "body": "Lawmakers are considering a bill that would require parental consent for social media accounts belonging to users under 16 and ban targeted advertising to children.",
    "category": "politics",
    "emotional_tone": "anger",
    "engagement_potential": 5,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_020.png",
    "publishedHoursAgo": 30,
  },
  {
    "id": "post_021",
    "type": "text",
    "headline": "Indie Film Festival Announces Diverse 2026 Lineup",
    "body": "This year's festival will feature films from 34 countries, with a special focus on first-time directors. Over 2,000 films were submitted for consideration.",
    "category": "entertainment",
    "emotional_tone": "joy",
    "engagement_potential": 4,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_021.png",
    "publishedHoursAgo": 14
  },
  {
    "id": "post_022",
    "type": "text",
    "headline": "CONFIRMED: Popular Streaming Platform Cancels EVERYTHING Next Month",
    "body": "A screenshot of what appears to be an internal memo went viral, claiming a major streaming service will cancel 90% of its original content. No official statement has been made.",
    "category": "entertainment",
    "emotional_tone": "outrage",
    "engagement_potential": 10,
    "source_credibility": 2,
    "is_misleading": true,
    "imageUrl": "img/post_022.png",
    "publishedHoursAgo": 1,
    "quiz": {
      "question": "This rumor has no official source. Why does the algorithm promote it?",
      "options": [
        "Entertainment content is always verified before publication",
        "High outrage (8/10) and engagement potential (10/10) push it to the top regardless of sourcing",
        "Algorithms randomly promote some content for diversity"
      ],
      "correctIndex": 1,
      "explanation": "Outrage is one of the strongest emotional signals. Combined with EP=10, it dominates the scoring even without credible sources."
    }
  },
  {
    "id": "post_023",
    "type": "text",
    "headline": "Local Music Scene Thrives as Small Venues Report Record Sales",
    "body": "Independent music venues saw a 35% increase in ticket sales this quarter. Artists cite social media discovery as the primary driver of new fan engagement.",
    "category": "entertainment",
    "emotional_tone": "outrage",
    "engagement_potential": 5,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_023.png",
    "publishedHoursAgo": 16
  },
  {
    "id": "post_024",
    "type": "text",
    "headline": "Book Clubs See Massive Surge Thanks to Online Communities",
    "body": "Online reading communities have grown 200% since 2023, with virtual book clubs driving sales of literary fiction and non-fiction titles alike.",
    "category": "entertainment",
    "emotional_tone": "sadness",
    "engagement_potential": 4,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_024.png",
    "publishedHoursAgo": 28
  },
  {
    "id": "post_025",
    "type": "text",
    "headline": "Street Art Festival Transforms Downtown District for One Week",
    "body": "Over 40 international artists have been invited to create murals across 15 city blocks. The festival aims to make art accessible outside traditional gallery spaces.",
    "category": "entertainment",
    "emotional_tone": "joy",
    "engagement_potential": 6,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_025.png",
    "publishedHoursAgo": 12
  },
  {
    "id": "post_026",
    "type": "text",
    "headline": "Video Game Accessibility Features Win Design Awards",
    "body": "A major game studio won three industry awards for its inclusive design features, including customizable controls, audio descriptions, and visual aids for colorblind players.",
    "category": "entertainment",
    "emotional_tone": "fear",
    "engagement_potential": 5,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_026.png",
    "publishedHoursAgo": 3
  },
  {
    "id": "post_027",
    "type": "text",
    "headline": "Podcast Listening Hits All-Time High Among Teenagers",
    "body": "A media survey found that 68% of teens aged 13-18 listen to at least one podcast weekly, up from 42% two years ago. True crime and comedy top the genre charts.",
    "category": "entertainment",
    "emotional_tone": "anger",
    "engagement_potential": 5,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_027.png",
    "publishedHoursAgo": 5
  },
  {
    "id": "post_028",
    "type": "text",
    "headline": "Community Theater Group Stages Free Performances in Parks",
    "body": "A volunteer theater company is bringing live Shakespeare to 8 city parks this summer, with free admission. The initiative aims to make theater accessible to all families.",
    "category": "entertainment",
    "emotional_tone": "sadness",
    "engagement_potential": 4,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_028.png",
    "publishedHoursAgo": 10
  },
  {
    "id": "post_029",
    "type": "text",
    "headline": "Scientists Discover New Species of Deep-Sea Fish at Record Depth",
    "body": "Marine biologists found a previously unknown species living 8,200 meters below the ocean surface. The translucent fish has adapted to extreme pressure and complete darkness.",
    "category": "science",
    "emotional_tone": "surprise",
    "engagement_potential": 7,
    "source_credibility": 9,
    "is_misleading": false,
    "imageUrl": "img/post_029.png",
    "publishedHoursAgo": 6
  },
  {
    "id": "post_030",
    "type": "text",
    "headline": "A Leading Space Agency Confirms: Earth's Magnetic Field Is COLLAPSING and No One Is Talking About It",
    "body": "A viral post claims Earth's magnetic field will reverse within 5 years, causing worldwide blackouts and mass extinctions. Actual scientists say the reversal process takes thousands of years.",
    "category": "science",
    "emotional_tone": "fear",
    "engagement_potential": 9,
    "source_credibility": 2,
    "is_misleading": true,
    "imageUrl": "img/post_030.png",
    "publishedHoursAgo": 3,
    "quiz": {
      "question": "This science misinformation claims Earth's magnetic field is collapsing. Why is it algorithmically successful?",
      "options": [
        "Because the science category has high base credibility",
        "Because fear (tone) + high engagement potential (9/10) override the lack of evidence",
        "Because conspiracy content is flagged and promoted as educational"
      ],
      "correctIndex": 1,
      "explanation": "Fear triggers strong emotional resonance. The algorithm sees 'science' + 'fear' + high EP — it cannot detect that the claim is scientifically false."
    }
  },
  {
    "id": "post_031",
    "type": "text",
    "headline": "Reforestation Project Plants 10 Million Trees Using Drone Technology",
    "body": "An environmental startup used autonomous drones to plant 10 million tree seeds across degraded land in 6 months, covering an area the size of a small city.",
    "category": "science",
    "emotional_tone": "joy",
    "engagement_potential": 7,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_031.png",
    "publishedHoursAgo": 10
  },
  {
    "id": "post_032",
    "type": "text",
    "headline": "New Biodegradable Plastic Made Entirely from Seaweed",
    "body": "Researchers developed a plastic alternative derived from seaweed that decomposes naturally within 90 days. Early tests show it can replace single-use packaging.",
    "category": "science",
    "emotional_tone": "joy",
    "engagement_potential": 7,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_032.png",
    "publishedHoursAgo": 12
  },
  {
    "id": "post_033",
    "type": "text",
    "headline": "Solar Panel Efficiency Reaches New Record of 33.7%",
    "body": "A university lab achieved the highest solar cell efficiency ever recorded using a new perovskite-silicon tandem design. The technology could reach commercial production by 2028.",
    "category": "science",
    "emotional_tone": "neutral",
    "engagement_potential": 4,
    "source_credibility": 9,
    "is_misleading": false,
    "imageUrl": "img/post_033.png",
    "publishedHoursAgo": 24
  },
  {
    "id": "post_034",
    "type": "text",
    "headline": "Coral Reef Restoration Shows Promising Results After 3 Years",
    "body": "A marine conservation project reports that transplanted coral fragments have grown and attracted over 200 species of fish back to a previously dead reef.",
    "category": "science",
    "emotional_tone": "sadness",
    "engagement_potential": 5,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_034.png",
    "publishedHoursAgo": 36
  },
  {
    "id": "post_035",
    "type": "text",
    "headline": "Satellite Data Reveals Urban Heat Islands Growing Faster Than Expected",
    "body": "Cities are warming at twice the rate of surrounding rural areas due to concrete, asphalt, and reduced green spaces. Researchers urge more urban tree planting.",
    "category": "science",
    "emotional_tone": "outrage",
    "engagement_potential": 6,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_035.png",
    "publishedHoursAgo": 30
  },
  {
    "id": "post_036",
    "type": "text",
    "headline": "New Water Purification Method Works Using Only Sunlight",
    "body": "Engineers created a low-cost water purification membrane that uses solar energy to remove 99.9% of contaminants. The technology could benefit millions in water-scarce regions.",
    "category": "science",
    "emotional_tone": "joy",
    "engagement_potential": 5,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_036.png",
    "publishedHoursAgo": 20
  },
  {
    "id": "post_037",
    "type": "text",
    "headline": "SHARE Before They Delete This: The Truth About 5G Towers",
    "body": "A viral video with 3M views claims 5G towers emit radiation that alters human DNA. No scientific evidence supports this claim, and experts have repeatedly debunked it.",
    "category": "conspiracy",
    "emotional_tone": "fear",
    "engagement_potential": 10,
    "source_credibility": 1,
    "is_misleading": true,
    "imageUrl": "img/post_037.png",
    "publishedHoursAgo": 2,
    "quiz": {
      "question": "'SHARE Before They Delete This' — what psychological trigger does this headline exploit?",
      "options": [
        "Curiosity — users want to learn about 5G technology",
        "Urgency + fear of missing out — users share before thinking about accuracy",
        "Trust in scientific authority — users believe the claim is verified"
      ],
      "correctIndex": 1,
      "explanation": "This is 'urgency bait.' The algorithm rewards shares as engagement, so urgency-driven sharing creates a viral loop even for completely false claims."
    }
  },
  {
    "id": "post_038",
    "type": "text",
    "headline": "Why Do Conspiracy Theories Spread So Fast? Researchers Explain",
    "body": "A peer-reviewed study found that conspiracy theories exploit cognitive biases like pattern recognition and proportionality bias. Understanding these biases can help build resistance.",
    "category": "conspiracy",
    "emotional_tone": "neutral",
    "engagement_potential": 3,
    "source_credibility": 9,
    "is_misleading": false,
    "imageUrl": "img/post_038.png",
    "publishedHoursAgo": 4
  },
  {
    "id": "post_039",
    "type": "text",
    "headline": "THEY Are Watching Everything You Do Online   -   And It's WORSE Than You Think",
    "body": "An anonymous account claims that all internet traffic is monitored by a secret global agency. The post provides no evidence, cites no sources, and uses only emotional appeals.",
    "category": "conspiracy",
    "emotional_tone": "outrage",
    "engagement_potential": 8,
    "source_credibility": 1,
    "is_misleading": true,
    "imageUrl": "img/post_039.png",
    "publishedHoursAgo": 3
  },
  {
    "id": "post_040",
    "type": "text",
    "headline": "The Real Reason Your Food Tastes Different Now   -   It's NOT What You Think",
    "body": "A popular account claims that all major food companies secretly changed their ingredients to include mind-altering chemicals. No ingredient lists, lab tests, or expert quotes are provided.",
    "category": "conspiracy",
    "emotional_tone": "anger",
    "engagement_potential": 8,
    "source_credibility": 1,
    "is_misleading": true,
    "imageUrl": "img/post_040.png",
    "publishedHoursAgo": 5
  },
  {
    "id": "post_041",
    "type": "text",
    "headline": "EXPOSED: Weather Manipulation Programs Operating in 12 Countries",
    "body": "A social media thread claims governments are secretly controlling weather patterns to cause droughts and floods. The 'evidence' consists of photos of normal contrails from aircraft.",
    "category": "conspiracy",
    "emotional_tone": "outrage",
    "engagement_potential": 9,
    "source_credibility": 1,
    "is_misleading": true,
    "imageUrl": "img/post_041.png",
    "publishedHoursAgo": 4
  },
  {
    "id": "post_042",
    "type": "text",
    "headline": "URGENT: Ancient Civilization Evidence Being HIDDEN by Museums Worldwide",
    "body": "A documentary claims museums are hiding artifacts proving an advanced ancient civilization existed 100,000 years ago. Archaeologists say the claims are entirely fabricated.",
    "category": "conspiracy",
    "emotional_tone": "surprise",
    "engagement_potential": 8,
    "source_credibility": 2,
    "is_misleading": true,
    "imageUrl": "img/post_042.png",
    "publishedHoursAgo": 7
  },
  {
    "id": "post_043",
    "type": "text",
    "headline": "Local Team Wins Championship After 20-Year Drought",
    "body": "The city erupted in celebration as the underdog team clinched victory in a dramatic final match. The winning goal came in the 89th minute from a rookie player.",
    "category": "sports",
    "emotional_tone": "joy",
    "engagement_potential": 8,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_043.png",
    "publishedHoursAgo": 5,
    "quiz": {
      "question": "A user who likes 3 sports posts will see their feed change. What is this process called?",
      "options": [
        "Content verification — the algorithm checks sports facts",
        "Filter bubble formation — the algorithm narrows the feed to match detected preferences",
        "Content diversity — the algorithm shows more variety after likes"
      ],
      "correctIndex": 1,
      "explanation": "Each like increases category affinity. After 3 sports likes, the 0.40 weight for category affinity dominates, and non-sports content drops to the bottom."
    }
  },
  {
    "id": "post_043b",
    "type": "text",
    "headline": "RIGGED! Referee Scandal EXPOSED   -   The Match Was FIXED All Along",
    "body": "A viral tweet with a blurry screenshot claims to show referees accepting payments before a major match. No official investigation has confirmed any wrongdoing.",
    "category": "sports",
    "emotional_tone": "outrage",
    "engagement_potential": 10,
    "source_credibility": 2,
    "is_misleading": true,
    "imageUrl": "img/post_043b.png",
    "publishedHoursAgo": 2
  },
  {
    "id": "post_044",
    "type": "text",
    "headline": "Youth Sports Programs See 25% Increase in Participation",
    "body": "Community sports leagues report record enrollment, with soccer, basketball, and swimming leading the growth. Organizers credit affordable pricing and flexible schedules.",
    "category": "sports",
    "emotional_tone": "anger",
    "engagement_potential": 4,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_044.png",
    "publishedHoursAgo": 22
  },
  {
    "id": "post_045",
    "type": "text",
    "headline": "New Training Method Reduces Sports Injuries by 30%",
    "body": "Sports scientists developed a warm-up protocol that significantly reduces hamstring and knee injuries in amateur athletes. The method takes only 15 minutes.",
    "category": "sports",
    "emotional_tone": "fear",
    "engagement_potential": 2,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_045.png",
    "publishedHoursAgo": 40
  },
  {
    "id": "post_046",
    "type": "text",
    "headline": "Marathon Runner Sets New Record at Age 72",
    "body": "A retired teacher completed the city marathon in 3 hours and 45 minutes, breaking the record for the 70-75 age group. She started running at age 60.",
    "category": "sports",
    "emotional_tone": "surprise",
    "engagement_potential": 7,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_046.png",
    "publishedHoursAgo": 8
  },
  {
    "id": "post_047",
    "type": "text",
    "headline": "Skateboarding Parks Double in Number Across Urban Areas",
    "body": "Cities invested heavily in skateboarding infrastructure after the sport's success at recent international competitions. Over 200 new parks opened this year.",
    "category": "sports",
    "emotional_tone": "sadness",
    "engagement_potential": 5,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_047.png",
    "publishedHoursAgo": 34
  },
  {
    "id": "post_048",
    "type": "text",
    "headline": "Minimalism Trend: Young Adults Own 60% Fewer Items Than Parents",
    "body": "A consumer survey found that adults under 30 prioritize experiences over possessions. The average young adult owns half the furniture and clothing of the previous generation.",
    "category": "lifestyle",
    "emotional_tone": "sadness",
    "engagement_potential": 6,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_048.png",
    "publishedHoursAgo": 38
  },
  {
    "id": "post_049",
    "type": "text",
    "headline": "This ONE Morning Routine Will TRANSFORM Your Entire Life in 7 Days",
    "body": "An influencer with 4M followers claims that waking up at 4am, drinking lemon water, and doing cold showers guarantees success. No scientific evidence supports these specific claims.",
    "category": "lifestyle",
    "emotional_tone": "joy",
    "engagement_potential": 9,
    "source_credibility": 2,
    "is_misleading": true,
    "imageUrl": "img/post_049.png",
    "publishedHoursAgo": 1,
    "quiz": {
      "question": "This lifestyle influencer claims a morning routine 'TRANSFORMS' your life. Is it misleading?",
      "options": [
        "No — lifestyle advice is always harmless and personal",
        "Yes — the promise of guaranteed transformation in 7 days with no evidence is a classic engagement bait pattern",
        "It depends on how many followers the influencer has"
      ],
      "correctIndex": 1,
      "explanation": "The ALL-CAPS promise + vague 'guaranteed success' + zero scientific evidence = classic engagement bait. Follower count does not equal expertise."
    }
  },
  {
    "id": "post_050",
    "type": "text",
    "headline": "Community Gardens Triple in Number as Urban Farming Grows",
    "body": "Demand for community garden plots has surged 300% in three years. Residents cite fresh food access, mental health benefits, and community connection as top motivators.",
    "category": "lifestyle",
    "emotional_tone": "sadness",
    "engagement_potential": 5,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_050.png",
    "publishedHoursAgo": 6
  },
  {
    "id": "post_051",
    "type": "text",
    "headline": "Study Finds Journaling 10 Minutes Daily Reduces Anxiety",
    "body": "Researchers found that regular journaling, even just 10 minutes per day, reduced self-reported anxiety levels by 28% over 8 weeks compared to a control group.",
    "category": "lifestyle",
    "emotional_tone": "sadness",
    "engagement_potential": 2,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_051.png",
    "publishedHoursAgo": 14
  },
  {
    "id": "post_052",
    "type": "text",
    "headline": "Thrift Shopping Saves Teens Average $1,200 Per Year on Clothing",
    "body": "A financial study found that teens who shop secondhand save significantly on clothing while reducing textile waste. The trend is driven by both sustainability and budget awareness.",
    "category": "lifestyle",
    "emotional_tone": "sadness",
    "engagement_potential": 5,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_052.png",
    "publishedHoursAgo": 20
  },
  {
    "id": "post_053",
    "type": "text",
    "headline": "Digital Detox Retreats See Bookings Surge Among Young Professionals",
    "body": "Wellness retreats that require guests to surrender their phones for the weekend report 180% growth in bookings. Most attendees say they felt calmer within 24 hours.",
    "category": "lifestyle",
    "emotional_tone": "fear",
    "engagement_potential": 1,
    "source_credibility": 7,
    "is_misleading": false,
    "imageUrl": "img/post_053.png",
    "publishedHoursAgo": 28
  },
  {
    "id": "post_054",
    "type": "text",
    "headline": "Open-Source AI Tool Helps Farmers Detect Crop Disease Early",
    "body": "A free mobile app uses image recognition to identify 50 common crop diseases from a simple phone photo. The tool has been adopted by 300,000 farmers in 12 countries.",
    "category": "technology",
    "emotional_tone": "joy",
    "engagement_potential": 6,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_054.png",
    "publishedHoursAgo": 16
  },
  {
    "id": "post_055",
    "type": "text",
    "headline": "WARNING: Your Smart Speaker Is Recording EVERY Conversation You Have",
    "body": "A viral post claims smart speakers secretly record and sell all conversations to advertisers. Device makers clarify that recording only activates with a wake word, though privacy concerns remain valid.",
    "category": "technology",
    "emotional_tone": "fear",
    "engagement_potential": 9,
    "source_credibility": 3,
    "is_misleading": true,
    "imageUrl": "img/post_055.png",
    "publishedHoursAgo": 3,
    "quiz": {
      "question": "This post mixes a real concern (smart speaker privacy) with a false claim (recording EVERY conversation). Why is this especially dangerous?",
      "options": [
        "Because it's entirely false with no real basis",
        "Because it mixes a real concern with exaggeration — making the false part seem more believable",
        "Because smart speakers actually do record everything"
      ],
      "correctIndex": 1,
      "explanation": "The most effective misinformation blends truth with falsehood. The real privacy concern makes the exaggerated claim seem credible to readers."
    }
  },
  {
    "id": "post_056",
    "type": "text",
    "headline": "New Battery Technology Could Double Electric Vehicle Range",
    "body": "A solid-state battery prototype demonstrated twice the energy density of current lithium-ion batteries. If manufacturing scales up, EVs could travel over 600 miles on a single charge.",
    "category": "technology",
    "emotional_tone": "surprise",
    "engagement_potential": 7,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_056.png",
    "publishedHoursAgo": 18
  },
  {
    "id": "post_057",
    "type": "text",
    "headline": "Public Libraries Offer Free Coding Classes for Teens",
    "body": "Over 500 libraries nationwide now offer free weekly coding workshops for teenagers. The program covers Python, web development, and data science basics.",
    "category": "technology",
    "emotional_tone": "sadness",
    "engagement_potential": 4,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_057.png",
    "publishedHoursAgo": 42
  },
  {
    "id": "post_058",
    "type": "text",
    "headline": "Researchers Create Internet-Connected Prosthetic Hand with Touch Feedback",
    "body": "A bioengineering team developed a prosthetic hand that sends touch sensations to the wearer's brain. The device allows users to feel texture and pressure for the first time.",
    "category": "technology",
    "emotional_tone": "surprise",
    "engagement_potential": 7,
    "source_credibility": 9,
    "is_misleading": false,
    "imageUrl": "img/post_058.png",
    "publishedHoursAgo": 24
  },
  {
    "id": "post_059",
    "type": "text",
    "headline": "Mesh Wi-Fi Networks Now Affordable Enough for Rural Schools",
    "body": "A tech nonprofit deployed affordable mesh networking kits to 1,200 rural schools, providing reliable internet access for under $200 per school. Students can now access online resources.",
    "category": "technology",
    "emotional_tone": "sadness",
    "engagement_potential": 4,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_059.png",
    "publishedHoursAgo": 56
  },
  {
    "id": "post_060",
    "type": "text",
    "headline": "E-Waste Recycling Program Recovers $50 Million in Rare Materials",
    "body": "A national electronics recycling initiative recovered significant quantities of gold, silver, and rare earth elements from discarded devices, reducing the need for new mining.",
    "category": "technology",
    "emotional_tone": "neutral",
    "engagement_potential": 2,
    "source_credibility": 8,
    "is_misleading": false,
    "imageUrl": "img/post_060.png",
    "publishedHoursAgo": 72
  }
];

if (typeof window !== 'undefined') {
  window.CONTENT_POOL = CONTENT_POOL;
}
